### ISSUE TITLE
Internal server error at broker prevent registering of resources.

### ISSUE THREAD

**Issue by sebplorenz** [International-Data-Spaces-Association/metadata-broker-open-core#52]
Internal server error at broker prevent registering of resources.

```

org.apache.jena.atlas.web.HttpException: 500 - Server Error


	at org.apache.jena.riot.web.HttpOp.exec(HttpOp.java:1091)


	at org.apache.jena.riot.web.HttpOp.execHttpPost(HttpOp.java:721)


	at org.apache.jena.rdfconnection.RDFConnectionRemote.lambda$doPutPost$9(RDFConnectionRemote.java:458)


	at org.apache.jena.rdfconnection.RDFConnectionRemote.exec(RDFConnectionRemote.java:668)


	at org.apache.jena.rdfconnection.RDFConnectionRemote.doPutPost(RDFConnectionRemote.java:453)


	at org.apache.jena.rdfconnection.RDFConnectionRemote.load(RDFConnectionRemote.java:366)


	at de.fraunhofer.iais.eis.ids.index.common.persistence.RepositoryFacade.addStatements(RepositoryFacade.java:143)


	at de.fraunhofer.iais.eis.ids.broker.core.common.persistence.ResourcePersistenceAndIndexing.addToTriplestore(ResourcePersistenceAndIndexing.java:264)


	at de.fraunhofer.iais.eis.ids.broker.core.common.persistence.ResourcePersistenceAndIndexing.updated(ResourcePersistenceAndIndexing.java:189)


 08-09-2021 11:28:04.175 [http-nio-8080-exec-2] ERROR de.fraunhofer.iais.eis.ids.component.core.MessageDispatcherhandle - Internal error occurred.


de.fraunhofer.iais.eis.ids.component.core.RejectMessageException: org.apache.jena.atlas.web.HttpException: 500 - Server Error


	at de.fraunhofer.iais.eis.ids.broker.core.common.persistence.ResourceMessageHandler.handleValidated(ResourceMessageHandler.java:110)


	at de.fraunhofer.iais.eis.ids.broker.core.common.persistence.ResourceMessageHandler.handleValidated(ResourceMessageHandler.java:22)


	at de.fraunhofer.iais.eis.ids.connector.commons.messagevalidation.ValidatingMessageHandler.handle(ValidatingMessageHandler.java:28)


	at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.handle(MessageDispatcher.java:86)


	at de.fraunhofer.iais.eis.ids.broker.core.common.persistence.ResourceMessageHandler.handleValidated(ResourceMessageHandler.java:84)


	at de.fraunhofer.iais.eis.ids.broker.core.common.persistence.ResourceMessageHandler.handleValidated(ResourceMessageHandler.java:22)


	at de.fraunhofer.iais.eis.ids.connector.commons.messagevalidation.ValidatingMessageHandler.handle(ValidatingMessageHandler.java:28)


	at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.handle(MessageDispatcher.java:86)


	at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.lambda$dispatch$2(MessageDispatcher.java:51)


	at java.base/java.util.Optional.map(Optional.java:265)


	at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.lambda$dispatch$2(MessageDispatcher.java:51)


	at java.base/java.util.Optional.map(Optional.java:265)


	at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.dispatch(MessageDispatcher.java:51)


	at de.fraunhofer.iais.eis.ids.component.core.DefaultComponent.process(DefaultComponent.java:45)


	at de.fraunhofer.iais.eis.ids.component.interaction.multipart.MultipartComponentInteractor.process(MultipartComponentInteractor.java:87)


	at de.fraunhofer.iais.eis.ids.component.protocol.http.server.ComponentController.processMessage(ComponentController.java:237)


	at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.dispatch(MessageDispatcher.java:51)


	at de.fraunhofer.iais.eis.ids.component.core.DefaultComponent.process(DefaultComponent.java:45)


	at de.fraunhofer.iais.eis.ids.component.interaction.multipart.MultipartComponentInteractor.process(MultipartComponentInteractor.java:87)


	at de.fraunhofer.iais.eis.ids.component.protocol.http.server.ComponentController.processMessage(ComponentController.java:237)


	at de.fraunhofer.iais.eis.ids.component.protocol.http.server.ComponentController.infrastructureLevelCommunication(ComponentController.java:205)


	at jdk.internal.reflect.GeneratedMethodAccessor165.invoke(Unknown Source)


	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.base/java.lang.reflect.Method.invoke(Method.java:566)


	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)


	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)


	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)


	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)


	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)


	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)


	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)


	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)


	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)


	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)


	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)


	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)


	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)


	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)


	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)


	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)


	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)


	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)


	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)


	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)


	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)


	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)


	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)


	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)


	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)


	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)


	at java.base/java.lang.Thread.run(Thread.java:829)


	at de.fraunhofer.iais.eis.ids.component.protocol.http.server.ComponentController.infrastructureLevelCommunication(ComponentController.java:205)


	at jdk.internal.reflect.GeneratedMethodAccessor165.invoke(Unknown Source)


	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)


	at java.base/java.lang.reflect.Method.invoke(Method.java:566)


	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)


	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)


	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)


	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)


	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)


	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)


	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)


	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)


	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)


	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)


	at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)


	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)


	at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)


	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)


	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)


	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)


	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)


	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)


	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)


	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)


	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)


	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)


	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)


	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)


	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)


	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)


	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)


	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)


	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)


	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)


	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)


	at java.base/java.lang.Thread.run(Thread.java:829)


Caused by: org.apache.jena.atlas.web.HttpException: 500 - Server Error


	at org.apache.jena.riot.web.HttpOp.exec(HttpOp.java:1091)


	at org.apache.jena.riot.web.HttpOp.execHttpPost(HttpOp.java:721)


	at org.apache.jena.rdfconnection.RDFConnectionRemote.lambda$doPutPost$9(RDFConnectionRemote.java:458)


	at org.apache.jena.rdfconnection.RDFConnectionRemote.exec(RDFConnectionRemote.java:668)


	at org.apache.jena.rdfconnection.RDFConnectionRemote.doPutPost(RDFConnectionRemote.java:453)


	at org.apache.jena.rdfconnection.RDFConnectionRemote.load(RDFConnectionRemote.java:366)


	at de.fraunhofer.iais.eis.ids.index.common.persistence.RepositoryFacade.addStatements(RepositoryFacade.java:143)


	at de.fraunhofer.iais.eis.ids.broker.core.common.persistence.ResourcePersistenceAndIndexing.addToTriplestore(ResourcePersistenceAndIndexing.java:264)


	at de.fraunhofer.iais.eis.ids.broker.core.common.persistence.ResourcePersistenceAndIndexing.updated(ResourcePersistenceAndIndexing.java:189)


	at de.fraunhofer.iais.eis.ids.broker.core.common.persistence.ResourceMessageHandler.handleValidated(ResourceMessageHandler.java:84)


	... 63 common frames omitted
```

**Comment by sebbader** [comment]
Hi @sebplorenz please provide us with a link to the Broker instance and the example request that causes the exception.

**Comment by NehaThawani44** [comment]
Also, please recheck the postman collection/connector you are using for sending messages. I have sent the details to you.

**Comment by sebplorenz** [comment]
Hi, I'm currently trying to register a resource at the DRM Test Broker: https://broker.test.mobilitydataspace.io
I'm using a DSC to register one of its resources. I tried with the DWD connector (DSC v 6.2.0) and with the DB connector (DSC v 6.1.3). Both fail.

**Comment by NehaThawani44** [comment]
@sebplorenz  Please share the connector registration and resource registration message so that we can also reproduce this issue.
