### ISSUE TITLE
Error: Unable to retrieve DAPS token

### ISSUE THREAD

**Issue by dileep-ramachandrarao** [International-Data-Spaces-Association/metadata-broker-open-core#57]
Hello,

Currently, I am trying to run broker locally using the docker-compose file as available in the repository. 
I had the image, which was available before from the registry in this repo: registry.gitlab.cc-asp.fraunhofer.de:4567/eis-ids/broker-open/core. Also, I tried to build the image locally too.
However, in both cases, for any request the broker throws "unable to retrieve DAPS token" error. 
I had this tested until last week and everything was working fine. So, this is something new.

Below are the logs:

`broker-core_1          | 15:29:02.816 [http-nio-8080-exec-3] INFO  de.fraunhofer.iais.eis.ids.component.ecosystemintegration.daps.DapsSecurityTokenProvider - Token needs to be fetched anew from DAPS
broker-core_1          | de.fraunhofer.iais.eis.ids.component.core.TokenRetrievalException: Unable to retrieve DAPS token.
broker-core_1          |        at de.fraunhofer.iais.eis.ids.component.ecosystemintegration.daps.DapsSecurityTokenProvider.getSecurityToken(DapsSecurityTokenProvider.java:96)
broker-core_1          |        at de.fraunhofer.iais.eis.ids.component.core.SecurityTokenProvider.getSecurityTokenAsDAT(SecurityTokenProvider.java:12)
broker-core_1          |        at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.handle(MessageDispatcher.java:69)
broker-core_1          |        at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.lambda$dispatch$2(MessageDispatcher.java:51)
broker-core_1          |        at java.base/java.util.Optional.map(Optional.java:265)
broker-core_1          |        at de.fraunhofer.iais.eis.ids.component.core.MessageDispatcher.dispatch(MessageDispatcher.java:51)
broker-core_1          |        at de.fraunhofer.iais.eis.ids.component.core.DefaultComponent.process(DefaultComponent.java:45)
broker-core_1          |        at de.fraunhofer.iais.eis.ids.component.interaction.multipart.MultipartComponentInteractor.process(MultipartComponentInteractor.java:87)
broker-core_1          |        at de.fraunhofer.iais.eis.ids.component.protocol.http.server.ComponentController.processMessage(ComponentController.java:237)
broker-core_1          |        at de.fraunhofer.iais.eis.ids.component.protocol.http.server.ComponentController.infrastructureLevelCommunication(ComponentController.java:205)
broker-core_1          |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
broker-core_1          |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
broker-core_1          |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
broker-core_1          |        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
broker-core_1          |        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
broker-core_1          |        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
broker-core_1          |        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
broker-core_1          |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
broker-core_1          |        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
broker-core_1          |        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
broker-core_1          |        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
broker-core_1          |        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
broker-core_1          |        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
broker-core_1          |        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
broker-core_1          |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:665)
broker-core_1          |        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
broker-core_1          |        at javax.servlet.http.HttpServlet.service(HttpServlet.java:750)
broker-core_1          |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
broker-core_1          |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core_1          |        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
broker-core_1          |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
broker-core_1          |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core_1          |        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
broker-core_1          |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
broker-core_1          |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
broker-core_1          |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core_1          |        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
broker-core_1          |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
broker-core_1          |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
broker-core_1          |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core_1          |        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
broker-core_1          |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
broker-core_1          |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
broker-core_1          |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core_1          |        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
broker-core_1          |        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
broker-core_1          |        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
broker-core_1          |        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
broker-core_1          |        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
broker-core_1          |        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
broker-core_1          |        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
broker-core_1          |        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
broker-core_1          |        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
broker-core_1          |        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
broker-core_1          |        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
broker-core_1          |        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
broker-core_1          |        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
broker-core_1          |        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
broker-core_1          |        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
broker-core_1          |        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
broker-core_1          |        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
broker-core_1          |        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
broker-core_1          |        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
broker-core_1          |        at java.base/java.lang.Thread.run(Thread.java:829)
broker-core_1          | Caused by: java.io.IOException: Unable to retrieve DAPS token (response code: 400)
broker-core_1          |  Response: {"error":"invalid_client","error_description":"Client unknown"}
broker-core_1          |        at de.fraunhofer.iais.eis.ids.component.ecosystemintegration.daps.DapsTokenRetriever.acquireAccessTokenFromDaps(DapsTokenRetriever.java:190)
broker-core_1          |        at de.fraunhofer.iais.eis.ids.component.ecosystemintegration.daps.DapsTokenRetriever.retrieveToken(DapsTokenRetriever.java:101)
broker-core_1          |        at de.fraunhofer.iais.eis.ids.component.ecosystemintegration.daps.DapsSecurityTokenProvider.getSecurityToken(DapsSecurityTokenProvider.java:94)
broker-core_1          |        ... 63 more`

**Comment by dileep-ramachandrarao** [comment]
Thanks for pointing the right certificate. After replacing it with a new one the error is resolved and is working fine locally.
Good to close this issue.
